### PR TITLE
Fix cue render order for ass/ssa.

### LINKED ISSUE #2124: ASS render in a wrong order.
### Version

Media3 1.5.1

### More version details

1.5.1 release version.

### Devices that reproduce the issue

Pixel 5

### Devices that do not reproduce the issue

None (I think)

### Reproducible in the demo app?

Yes

### Reproduction steps

Chose a video with a customer ass.

Play

### Expected result

The  red latter should render behind the white, and before the gray.

Image

### Actual result

The gray is before the white, and red before all.

Image

### Media

The sample will post to media email later.

### Bug Report

- [x] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

### PR DESCRIPTION
**Pull request by peerless2012**
This should fix #2124 
* Add layer in cue and output.
* Add layer support for ssa parser.

### CODE REVIEW

**Comment by tonihei** [comment]
@icbaker Could you take a look? Thanks!

File: libraries/exoplayer/src/main/java/androidx/media3/exoplayer/text/MergingCuesResolver.java [hunk 1]
```diff
@@ -52,6 +52,12 @@
           .compound(
               Ordering.<Long>natural().reverse().onResultOf((CuesWithTiming c) -> c.durationUs));
 
+  /**
+   * An {@link Ordering} which sorts cues in ascending layer priority
+   */
+  private static final Ordering<Cue> CUES_LAYER_PRIORITY_COMPARATOR =
+      Ordering.<Integer>natural().onResultOf(c -> c.layer);
```
Comment (icbaker) [inline libraries/exoplayer/src/main/java/androidx/media3/exoplayer/text/MergingCuesResolver.java:59]: I think this logic should be part of `CUES_DISPLAY_PRIORITY_COMPARATOR` rather than a separate `Ordering` object

File: libraries/common/src/main/java/androidx/media3/common/text/Cue.java [hunk 2]
```diff
@@ -309,6 +309,11 @@ public final class Cue {
    */
   public final float shearDegrees;
 
+  /**
+   * The layer for cue, the larger cue will render above the smaller cue.
+   */
+  public final int layer;
```
Comment (icbaker) [inline libraries/common/src/main/java/androidx/media3/common/text/Cue.java:315]: nit: TTML (which has a much more robust & unambiguous spec than SSA) uses the name `zIndex` for this. It seems to have the same "higher index renders above lower index" semantics.

Shall we use that nomenclature here? So `Cue.zIndex`

We should keep the `layer` terminology everywhere in the `ssa` package.

File: libraries/common/src/main/java/androidx/media3/common/text/Cue.java [hunk 3]
```diff
@@ -806,6 +817,21 @@ public Builder setShearDegrees(float shearDegrees) {
...
+    public Builder setLayer(int layer) {
+      this.layer = layer;
+      return this;
+    }
+
+    /**
+     * Gets the layer for this Cue.
+     */
+    @Pure
+    public @VerticalType int getLayer() {
```
Comment (icbaker) [inline libraries/common/src/main/java/androidx/media3/common/text/Cue.java:831]: If this isn't needed I suggest we remove it

File: libraries/extractor/src/main/java/androidx/media3/extractor/text/ssa/SsaParser.java [hunk 4]
```diff
@@ -361,6 +369,19 @@ private void parseDialogueLine(
...
+  /**
+   * Parse int in SSA.
+   * @param intString The string to parse.
+   * @return The parsed int.
+   */
+  private static int parseInt(String intString) {
+    try {
+      return Integer.parseInt(intString.trim());
+    } catch (Exception exception) {
+      return C.LENGTH_UNSET;
```
Comment (icbaker) [inline libraries/extractor/src/main/java/androidx/media3/extractor/text/ssa/SsaParser.java:381]: I think we should default to `0` here for `layer`, same as `Cue`

That probably means you need to either return `null` here, or take a default value as a parameter, or don't define this general purpose function and just in-line it for the layer case.

I'd suggest in-lining

File: libraries/ui/src/main/java/androidx/media3/ui/SubtitlePainter.java [hunk 5]
```diff
@@ -184,7 +185,8 @@ public void draw(
         && this.parentLeft == cueBoxLeft
         && this.parentTop == cueBoxTop
         && this.parentRight == cueBoxRight
-        && this.parentBottom == cueBoxBottom) {
+        && this.parentBottom == cueBoxBottom
+        && this.cueLayer == cue.layer) {
```
Comment (icbaker) [inline libraries/ui/src/main/java/androidx/media3/ui/SubtitlePainter.java:189]: What happens if you remove this comparison? It seems a bit surprising you need to store `cueLayer` into a field and then **only** use it in this comparison. I think all the other fields being compared here are then later used to compute the layout (hence they need to be checked to see if the layout needs to be invalidated).

File: libraries/extractor/src/main/java/androidx/media3/extractor/text/CuesWithTiming.java [hunk 6]
```diff
@@ -68,7 +75,7 @@ public class CuesWithTiming {
 
   /** Creates an instance. */
   public CuesWithTiming(List<Cue> cues, long startTimeUs, long durationUs) {
-    this.cues = ImmutableList.copyOf(cues);
+    this.cues = ImmutableList.sortedCopyOf(CUES_LAYER_PRIORITY_COMPARATOR, cues);
```
Comment (icbaker) [inline libraries/extractor/src/main/java/androidx/media3/extractor/text/CuesWithTiming.java:78]: `CuesWithTiming.cues` has no documented ordering behaviour wrt layout on screen.

`CuesGroup.cue` **does** document how ordering affects layout.

Is this reordering needed here? It seems it shouldn't be, since the field has no ordering guarantee. Maybe this should be moved to a point where a `CueGroup` is being created?

File: libraries/exoplayer/src/main/java/androidx/media3/exoplayer/text/MergingCuesResolver.java (hunk 1 above)
Comment (peerless2012) [reply libraries/exoplayer/src/main/java/androidx/media3/exoplayer/text/MergingCuesResolver.java:59]: CUES_DISPLAY_PRIORITY_COMPARATOR with CuesWithTiming, but the layer is in Cue, not in CuesWithTiming.

File: libraries/common/src/main/java/androidx/media3/common/text/Cue.java (hunk 2 above)
Comment (peerless2012) [reply libraries/common/src/main/java/androidx/media3/common/text/Cue.java:315]: I'm not familiar with TTML, but I can chenage the layer to zIndex, if you think it is more stand.

File: libraries/common/src/main/java/androidx/media3/common/text/Cue.java (hunk 3 above)
Comment (peerless2012) [reply libraries/common/src/main/java/androidx/media3/common/text/Cue.java:831]: > If this isn't needed I suggest we remove it

Yes, I forget to delete the type annotation.

File: libraries/extractor/src/main/java/androidx/media3/extractor/text/ssa/SsaParser.java (hunk 4 above)
Comment (peerless2012) [reply libraries/extractor/src/main/java/androidx/media3/extractor/text/ssa/SsaParser.java:381]: parseInt is a general method, and I will set layer to 0 when the result is unset in line 333.

File: libraries/ui/src/main/java/androidx/media3/ui/SubtitlePainter.java (hunk 5 above)
Comment (peerless2012) [reply libraries/ui/src/main/java/androidx/media3/ui/SubtitlePainter.java:189]: Due to your explain, it seems no need to compair the layer.

File: libraries/extractor/src/main/java/androidx/media3/extractor/text/CuesWithTiming.java (hunk 6 above)
Comment (peerless2012) [reply libraries/extractor/src/main/java/androidx/media3/extractor/text/CuesWithTiming.java:78]: Yes, you are right. That's a good way. and it seems there is no need to modify the MergingCuesResolver.

**Comment by peerless2012** [comment]
@icbaker hello, please make a review for the new commit, and hope this pr can merge to 1.6.0 final release.

File: libraries/extractor/src/main/java/androidx/media3/extractor/text/ssa/SsaParser.java (hunk 4 above)
Comment (icbaker) [reply libraries/extractor/src/main/java/androidx/media3/extractor/text/ssa/SsaParser.java:381]: `parseInt` may be trying to be a general method, but `LENGTH_UNSET` (-1) is not a generally safe 'invalid' value for all possible integer fields (i.e. there may be some integer fields where we expect to read -1 from the file). In fact, tbh it's not clear to me that -1 (or any negative number) is an invalid value for `layer`. The SSA "spec" I'm reading says:
> Layer (any integer)

Which could reasonably be interpreted to include negative numbers.

So please either in-line this method (my preference) or return `null` when the parsing fails.

**Comment by icbaker** [comment]
Please can you add some tests for this?

I suggest:
1. Some parsing tests in `SsaParserTest` (including negative & unparseable layer values) - assert that the right value ends up in `Cue.zIndex`
2. An end-to-end test in `SubtitlePlaybackTest`? This will cover both your parsing code and the re-ordering in the `CueGroup` constructor.

For (2) I suggest you craft an SSA test file that has cues overlapping in time with different layer values, to demonstrate why the re-ordering has to be done 'outside' `SsaParser`.

**Comment by peerless2012** [comment]
I add `parseLayer` and `parseInvalidLayer` in `SsaParserTest` to cover the layer value in ssa.

How can I add a test in `SubtitlePlaybackTest`? I have no idea.

**Comment by icbaker** [comment]
Thanks for adding the tests to `SsaParserTest`, I've added `SsaPlaybackTest` to cover the layer-based re-ordering inside `CueGroup`.

**Comment by peerless2012** [comment]
> I'm going to send this for internal review now. You may see some more commits being added as I make changes in response to review feedback. Please refrain from pushing any more substantive changes as it will complicate the internal review - thanks!

Thanks a lot for your help. 🫶
